name: flutter_cookie_consent
description: "A Flutter package for implementing GDPR-compliant cookie consent banners and privacy preferences."
version: 1.1.0
homepage: https://github.com/redhotsixbull/flutter_cookie_consent
repository: https://github.com/redhotsixbull/flutter_cookie_consent.git
documentation: https://github.com/redhotsixbull/flutter_cookie_consent#readme
topics:
  - flutter
  - cookie
  - consent
  - gdpr
  - privacy

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.redhotsixbull.flutter_cookie_consent
        pluginClass: FlutterCookieConsentPlugin
      ios:
        pluginClass: FlutterCookieConsentPlugin
      web:
        pluginClass: FlutterCookieConsentWeb
        fileName: flutter_cookie_consent_web.dart
